version: "3.7"
services:
  nginx-balancer:
    depends_on:
      - mattermost
      - redmine
      - grafana
    image: nginx:1.25.2-alpine
    restart: unless-stopped
    volumes:
      - ./nginx-balancer/logs/nginx:/var/log/nginx
      - ./nginx-balancer/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-balancer:/etc/nginx
    networks:
      - redmine-network
      - mattermost-network
      - prometheus-network
    ports:
      - "80:80"
      - "8443:8443"

  rocketchat:
   image

  mongodb-rocketchat:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: rocketchat
      MONGO_INITDB_ROOT_PASSWORD: password

  postgresql-redmine:
    image: postgres:15.4-alpine
    restart: unless-stopped
    environment:
      TX: UTC
      POSTGRES_USER: redmineuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: redmine
    networks:
      - redmine-network
      - prometheus-network
    volumes:
      - ./postgresql:/postgresql

  redmine:
    depends_on:
      - postgresql-redmine
    image: redmine:5.0.5-alpine
    restart: unless-stopped
    environment:
       REDMINE_DB_POSTGRES: postgresql-redmine
       REDMINE_DB_USERNAME: redmineuser
       REDMINE_DB_PASSWORD: password
       REDMINE_DB_DATABASE: redmine
       REDMINE_SECRET_KEY_BASE: secretkey
    networks:
      - redmine-network
    volumes:
       - ./redmine/plugins:/usr/src/redmine/plugins
       - ./redmine/themes:/usr/src/redmine/public/themes
       - ./redmine/data:/usr/src/redmine/files

  prometheus:
    depends_on:
      - nginx-balancer
      - postgresql-mattermost
      - postgresql-redmine
      - mattermost
      - redmine
      - grafana
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - prometheus-network
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml

  postgresql-grafana:
    image: postgres:15.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: grafana
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgresql:/postgresql
    networks:
      - prometheus-network

  grafana:
    depends_on:
      - postgresql-grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      GF_PATHS_CONFIG: /etc/grafana/grafana.ini
      GF_SERVER_ROOT_URL: http://91cb5acd148.vps.myjino.ru/grafana/
      GF_SERVER_SERVE_FROM_SUB_PATH: true
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: postgresql-grafana:5432
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: grafana
      GF_DATABASE_PASSWORD: password
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    networks:
      - prometheus-network

networks:
  prometheus-network:
    driver: bridge
  mattermost-network:
    driver: bridge
  redmine-network:
    driver: bridge
